// import data from "../utils/data";
import { 
  Button,
  Card,
  CardActionArea, 
  CardActions, 
  CardContent, 
  CardMedia, 
  Grid, 
  Typography
} from "@material-ui/core";
import NextLink from 'next/link';
import Layout from "../components/Layout";
import db from "../utils/db";
import Product from "../models/Product";
import Product2 from "../models/Product2";
import axios from "axios";
import { useRouter } from "next/router";
import { useContext } from "react";
import { Store } from "../utils/Store";

export default function Home(props) {
  const router = useRouter ();
  const { state, dispatch } = useContext ( Store );
  const { products } = props;
  const addToCartHandler = async (product) => {
    const existItem = state.cart.cartItems.find(x=>x._id === product._id);
    const quantity = existItem ? existItem.quantity + 1 : 1;
    const { data } = await axios.get(`/api/products/${product._id}`);
    if(data.countInStock < quantity) {
      window.alert ('Maaf. Produk Telah Habis');
      return;
    }
    dispatch({ type: 'CART_ADD_ITEM', payload: { ...product, quantity} });
    router.push('/cart');
  };
  const { products1 } = props;
  const addToCartHandler1 = async (product0) => {
    const { data } = await axios.get(`/api/products2/${product0._id}`);
    if(data.countInStock <= 0) {
      window.alert ('Maaf. Produk Telah Habis');
      return;
    }
    const existItem = state.cart.cartItems.find(x=>x._id === product0._id);
    const quantity = existItem ? existItem.quantity + 1 : 1;
    dispatch({ type: 'CART_ADD_ITEM', payload: { ...product0, quantity} });
    router.push('/cart');
  };
  return (
    <Layout>
      <div>
        <h1>Bunga Papan</h1>
        <Grid container spacing={3}>
          {products.map((product) => (
            <Grid 
              item 
              md={4} 
              key={product.name}
            >
              <Card>
                <NextLink href={`/product/${product.slug}`} passHref>
                  <CardActionArea>
                    <CardMedia 
                      component="img"
                      image={product.image}
                      title={product.name}
                    ></CardMedia>
                    <CardContent>
                      <Typography>
                        {product.name}
                      </Typography>
                      <Typography>
                        Rp.{product.price}
                      </Typography>
                    </CardContent>
                  </CardActionArea>
                </NextLink>
                <CardActions>
                  <Button
                    size="small" 
                    color="primary"
                    variant="contained"
                    onClick={() => addToCartHandler(product)}
                  >
                    Add To Cart
                  </Button>
                </CardActions>
              </Card>
            </Grid>
          ))}
        </Grid>
        <h1>Bunga Rotan</h1>
        <Grid container spacing={3}>
          {products1.map((product0) => (
            <Grid 
              item 
              md={4} 
              key={product0.name}
            >
              <Card>
                <NextLink href={`/product2/${product0.pid}`} passHref>
                  <CardActionArea>
                    <CardMedia 
                      component="img"
                      image={product0.image}
                      title={product0.name}
                    ></CardMedia>
                    <CardContent>
                      <Typography>
                        {product0.name}
                      </Typography>
                      <Typography>
                        Rp.{product0.price}
                      </Typography>
                    </CardContent>
                  </CardActionArea>
                </NextLink>
                <CardActions>
                  <Button
                    size="small" 
                    color="primary"
                    variant="contained"
                    onClick={() => addToCartHandler1(product0)}
                  >
                    Add To Cart
                  </Button>
                </CardActions>
              </Card>
            </Grid>
          ))}
        </Grid>
      </div>
    </Layout>
    
  )
}

export async function getServerSideProps() {
  await db.connect();
  const products = await Product.find({}).lean();
  const products1 = await Product2.find({}).lean();
  await db.disconnect();
  return {
    props:{
      products: products.map(db.convertDocToObj),
      products1: products1.map(db.convertDocToObj),
    },
  };
}

{/*import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}*/}
